on:
    workflow_call:
      inputs:
        playbook:
          required: true
          type: string
          description: ansible playbook to be executed
        checkout_software:
          required: true
          type: boolean
          description: Checkout software repositorie
          default: false
        site:
          required: true
          type: string
          description: site to execute against
        additional_parameters:
          type: string
          description: Additional Parameters to Ansible command
        ansible_verbose_logging:
          type: string
          default: 'false'
          description: Enable or disable verbose logging
          required: false
      secrets:
        sudo_password:  
        mastertoken:
        vault_password:

jobs:
  london:
    runs-on: "${{ inputs.site }}"
    name: "${{ inputs.playbook }}"
    defaults:
      run:
        working-directory: "${{ github.event.repository.name }}"
    env:
      verbose_logs: ""
    steps:
      - name: Checkout Repository (${{ github.event.repository.name }})
        uses: actions/checkout@v4
        with:
          path: "${{ github.event.repository.name }}"
      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-core'
        if: ${{ github.event.repository.name != 'ansible-core' }}
      - name: Checkout Repository (ansible-vault)
        uses: actions/checkout@v4
        with:
          path: ansible-vault
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-vault'
      - name: Checkout Repository (ansible-roles)
        uses: actions/checkout@v4
        with:
          path: ansible-roles
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-roles'
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Populate Vault Password File
        run: echo $PASS > ~/.vault
        shell: bash
        env:
          PASS: ${{ secrets.VAULT_PASSWORD }}
      - name: Set Verbosity
        run: echo "verbose_logs=-vvv" >> $GITHUB_ENV
        if: ${{ inputs.ansible_verbose_logging  == 'true' }}
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml ${{ inputs.additional_parameters }} ${{ env.verbose_logs}} --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}"
      - name: Cleanup Vault Password File
        run: rm ~/.vault
        if: always()
