name: Template - Deploy Playbook

on:
  workflow_call:
    inputs:
      runner: 
        required: true
        type: string
        description: runner to execute job on
      playbook: 
        required: true
        type: string
        description: ansible playbook to be executed
      rolename:
        type: string
        description: non-mandatory variable used for playbooks that deploy a specific role.
      group:
        type: string
        description: non-mandatory variable used for playbooks that deploy to a specific inventory group.
    secrets:
      sudo_password:  
      mastertoken:

jobs:
  Execute-Playbook:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: infrastructure/
    steps:
      - name: Checkout Repository (infrastructure)
        uses: actions/checkout@v4
        with:
          path: infrastructure
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}, rolename=${{ inputs.rolename }}", , group=${{ inputs.group }}"
