name: Standard Ansible Workflow

on:
  workflow_call:
    inputs:
      ansible_playbook:
        required: true
        type: string
        description: ansible playbook to be executed
      ansible_additional_parameters:
        type: string
        description: Additional Parameters to Ansible command
      ansible_verbose_logging:
        type: string
        description: Ansible Verbose Logging Enabled
        default: 'false'
        required: false
      runs-on:
        type: string
        description: Site used for job execution on non multisite jobs
        default: 'london'
      checkout_vault:
        type: string
        description: Checkout ansible-vault repository
        default: 'true'
        required: false
      azure_login:
        type: string
        description: Azure Login Required
        default: 'false'
        required: false
    secrets:
      auth_token:
      ansible_vault_password:
      arm_client_id:
        required: false
      arm_client_secret:
        required: false
      arm_tenant_id:
        required: false
jobs:
  ansible:
    runs-on: "${{ inputs.runs-on }}"
    name: "${{ inputs.ansible_playbook }}"
    defaults:
      run:
        working-directory: "${{ github.event.repository.name }}"
    env:
      verbose_logs: ""
    steps:
      - name: Checkout Repository (${{ github.event.repository.name }})
        uses: actions/checkout@v4
        with:
          path: "${{ github.event.repository.name }}"

      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          token: ${{secrets.auth_token}}
          ref: 'main'
          repository: 'epichouse/ansible-core'
        if: ${{ github.event.repository.name != 'ansible-core' }}

      - name: Checkout Repository (ansible-vault)
        uses: actions/checkout@v4
        with:
          path: ansible-vault
          token: ${{secrets.auth_token}}
          ref: 'main'
          repository: 'epichouse/ansible-vault'
        if: ${{ inputs.checkout_vault == 'true' }}

      - name: Checkout Repository (ansible-roles)
        uses: actions/checkout@v4
        with:
          path: ansible-roles
          token: ${{secrets.auth_token}}
          ref: 'main'
          repository: 'epichouse/ansible-roles'

      - name: Azure Login
        run: |
          az login \
          --service-principal \
          -t ${{ secrets.ARM_TENANT_ID }} \
          -u ${{secrets.ARM_CLIENT_ID}} \
          -p ${{ secrets.ARM_CLIENT_SECRET }} \
        if: ${{ inputs.azure_login == 'true' }}

      - name: Enable Verbose Flag
        run: |
          echo "verbose_logs=-vvv" >> $GITHUB_ENV
        if: ${{ inputs.ansible_verbose_logging  == 'true' }}

      - name: Generate Vault Password File
        run: |
          echo $PASS > ~/.vault
        shell: bash
        env:
          PASS: ${{ secrets.ansible_vault_password }}

      - name: Output Ansible Inventory
        run: |
          ansible-inventory --graph

      - name: Run Playbook
        run: |
          ansible-playbook ${{ inputs.ansible_playbook }} \
          ${{ inputs.ansible_additional_parameters }} \
          ${{ env.verbose_logs}} \

      - name: Cleanup Vault Password File
        run: rm ~/.vault
        if: always()