name: Template - Execute Ansible Role

on:
  workflow_call:
    inputs:
      rolepath:
        required: true
        type: string
        description: Role to execute
      rolehosts:
        required: true
        type: string
        description: Hosts to execute role against
      multisite:
        type: boolean
        description: Multisite Job or single server?
        default: true
      site:
        type: string
        description: Site used for job execution on non multisite jobs
    secrets:
      sudo_password:  
      mastertoken:
jobs:
  multisite:
    uses: ./.github/workflows/step-multisite-role.yaml
    if: inputs.multisite == true
    with:
      rolepath: ${{ inputs.rolepath }}
      rolehosts: ${{ inputs.rolehosts }}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}
  singlesite:
    uses: ./.github/workflows/step-singlesite-role.yaml
    if: inputs.multisite == false
    with:
      rolepath: ${{ inputs.rolepath }}
      rolehosts: ${{ inputs.rolehosts }}
      site: ${{ inputs.site }}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}