name: Template - Deploy Playbook

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: 'main'
      playbook: 
        required: true
        type: string
      rolename:
        type: string
      roletype:
        type: string
    secrets:
      sudo_password:  
      mastertoken:

jobs:
  Ansible:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ansible-core/
    steps:
      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          repository: 'epichouse/ansible-core.git'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Checkout Repository (ansible-servers)
        uses: actions/checkout@v4
        if: ${{ inputs.roletype }} == 'server'
        with:
          path: ansible-servers
          repository: 'epichouse/ansible-servers.git'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}, rolename=${{ inputs.rolename }} roletype=${{ inputs.roletype }}"