name: Template - Deploy Playbook

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: 'main'
      playbook: 
        required: true
        type: string

jobs:
  Ansible:
    runs-on: self-hosted
    #defaults:
    #  run:
    #    working-directory: ./ansible
    steps:
      - name: Checkout Repository (Ansible)
        uses: actions/checkout@v4
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml