name: Template - Execute Ansible Role

on:
  workflow_call:
    inputs:
      playbook:
        required: true
        type: string
        description: ansible playbook to be executed
      multisite:
        type: boolean
        description: Multisite Job or single server?
        default: true
      site:
        type: string
        description: Site used for job execution on non multisite jobs
      checkout_software:
        required: false
        type: boolean
        description: Checkout software repositories
        default: false
    secrets:
      sudo_password:  
      mastertoken:
jobs:
  multisite:
    uses: ./.github/workflows/step-multisite-playbook.yaml
    if: inputs.multisite == true
    with:
      playbook: ${{ inputs.playbook }}
      checkout_software: ${{ inputs.checkout_software }}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}