name: Template - Execute Ansible Role

on:
  workflow_call:
    inputs:
      playbook:
        required: true
        type: string
        description: ansible playbook to be executed
      multisite:
        type: boolean
        description: Multisite Job or single server?
        default: true
      site:
        type: string
        description: Site used for job execution on non multisite jobs
      checkout_software:
        required: false
        type: boolean
        description: Checkout software repositories
        default: false
      additional_parameters:
        type: string
        description: Additional Parameters to Ansible command
      ansible_verbose_logging:
        type: string
        description: Ansible Verbose Logging Enabled
        default: 'false'
        required: false
    secrets:
      sudo_password:  
      mastertoken:
      vault_password:
jobs:
  multisite:
    uses: ./.github/workflows/ansible-playbook.multisite.yaml
    if: inputs.multisite == true
    with:
      playbook: ${{ inputs.playbook }}
      checkout_software: ${{ inputs.checkout_software }}
      additional_parameters: ${{ inputs.additional_parameters }}
      ansible_verbose_logging: ${{inputs.ansible_verbose_logging}}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}
      vault_password: ${{ secrets.vault_password }}
  singlesite:
    uses: ./.github/workflows/ansible-playbook.singlesite.yaml
    if: inputs.multisite == false
    with:
      playbook: ${{ inputs.playbook }}
      site: ${{ inputs.site }}
      checkout_software: ${{ inputs.checkout_software }}
      additional_parameters: ${{ inputs.additional_parameters }}
      ansible_verbose_logging: ${{inputs.ansible_verbose_logging}}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}
      vault_password: ${{ secrets.vault_password }}