name: Template - Deploy Playbook

on:
  workflow_call:
    inputs:
      playbook: 
        required: true
        type: string
        description: ansible playbook to be executed
      rolename:
        type: string
        description: non-mandatory variable used for playbooks that deploy a specific role.
    secrets:
      sudo_password:  
      mastertoken:

jobs:
  Execute-Playbook:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ansible-core/
    steps:
      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          repository: 'epichouse/ansible-core'
          token: ${{secrets.mastertoken}}
      - name: Checkout Repository (ansible-servers)
        uses: actions/checkout@v4
        with:
          path: ansible-servers
          repository: 'epichouse/ansible-servers'
          token: ${{secrets.mastertoken}}
        if: ${{github.repository == 'epichouse/ansible-servers'}}
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Run Playbook (Check Only)
        if: github.ref != 'refs/heads/main'
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}, rolename=${{ inputs.rolename }}" --check
      - name: Run Playbook
        if: github.ref == 'refs/heads/main'
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}, rolename=${{ inputs.rolename }}"