name: Template - Execute Ansible Role

on:
  workflow_call:
    inputs:
      ansible_playbook:
        required: true
        type: string
        description: ansible playbook to be executed
      multisite:
        type: boolean
        description: Multisite Job or single server?
        default: true
      site:
        type: string
        description: Site used for job execution on non multisite jobs
      ansible_additional_parameters:
        type: string
        description: Additional Parameters to Ansible command
      ansible_verbose_logging:
        type: string
        description: Ansible Verbose Logging Enabled
        default: 'false'
        required: false
    secrets:
      sudo_password:  
      mastertoken:
      vault_password:
      arm_client_id:
      arm_client_secret:
      arm_tenant_id:
jobs:
  multisite:
    uses: ./.github/workflows/ansible-playbook.multisite.yaml
    if: inputs.multisite == true
    with:
      ansible_playbook: ${{ inputs.ansible_playbook }}
      ansible_additional_parameters: ${{ inputs.ansible_additional_parameters }}
      ansible_verbose_logging: ${{inputs.ansible_verbose_logging}}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}
      vault_password: ${{ secrets.vault_password }}
      arm_client_id: ${{ secrets.arm_client_id }}
      arm_client_secret: ${{ secrets.arm_client_secret }}
      arm_tenant_id: ${{ secrets.arm_tenant_id }}
  singlesite:
    uses: ./.github/workflows/ansible-playbook.singlesite.yaml
    if: inputs.multisite == false
    with:
      ansible_playbook: ${{ inputs.ansible_playbook }}
      site: ${{ inputs.site }}
      ansible_additional_parameters: ${{ inputs.ansible_additional_parameters }}
      ansible_verbose_logging: ${{inputs.ansible_verbose_logging}}
    secrets:
      sudo_password: ${{ secrets.sudo_password }}
      mastertoken: ${{ secrets.mastertoken }}
      vault_password: ${{ secrets.vault_password }}
      arm_client_id: ${{ secrets.arm_client_id }}
      arm_client_secret: ${{ secrets.arm_client_secret }}
      arm_tenant_id: ${{ secrets.arm_tenant_id }}