name: Template - Build & Publish Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      image_name:
        required: true
        type: string
      build_path:
        required: true
        type: string
jobs:
  build:
    runs-on: london
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ${{ inputs.build_path }}/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image with env tag
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ inputs.image_name }}"
          push: true
          tags: ghcr.io/${{ github.repository }}/${{inputs.image_name}}:${{ inputs.image_tag }}
          file: ./dockerfile  # Path to the Dockerfile
