name: Template - Build & Publish Docker Image

on:
  workflow_call:
    inputs:
      docker_env:
        required: true
        type: string
      docker_project:
        required: true
        type: string

jobs:
  build:
    runs-on: london
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: docker-images/${{ inputs.docker_project }}/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image with env tag
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ inputs.docker_project }}"
          push: true
          tags: ghcr.io/${{ github.repository }}/${{inputs.docker_project}}:${{ inputs.docker_env }}
          file: ./dockerfile  # Path to the Dockerfile
