on:
    workflow_call:
      inputs:
        playbook:
            required: true
            type: string
            description: ansible playbook to be executed
        checkout_software:
            required: true
            type: boolean
            description: Checkout software repositorie
            default: false
        additional_parameters:
          type: string
          description: Additional Parameters to Ansible command
      secrets:
        sudo_password:  
        mastertoken:
        vault_password:

jobs:
  london:
    runs-on: london
    name: london
    defaults:
      run:
        working-directory: "${{ github.event.repository.name }}"
    steps:
      - name: Checkout Repository ("${{ github.event.repository.name }}")
        uses: actions/checkout@v4
        with:
          path: "${{ github.event.repository.name }}"
      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-core'
      - name: Checkout Repository (ansible-roles)
        uses: actions/checkout@v4
        with:
          path: ansible-roles
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-roles'
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Populate Vault Password File
        run: echo $PASS > ~/.vault
        shell: bash
        env:
          PASS: ${{ secrets.VAULT_PASSWORD }}
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml ${{ inputs.additional_parameters }} --tags london --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}"
      - name: Cleanup Vault Password File
        run: rm ~/.vault
        if: always()
  manchester:
    runs-on: manchester
    name: manchester
    defaults:
      run:
        working-directory: "${{ github.event.repository.name }}"
    steps:
      - name: Checkout Repository ("${{ github.event.repository.name }}")
        uses: actions/checkout@v4
        with:
          path: "${{ github.event.repository.name }}"
      - name: Checkout Repository (ansible-core)
        uses: actions/checkout@v4
        with:
          path: ansible-core
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-core'
      - name: Checkout Repository (ansible-roles)
        uses: actions/checkout@v4
        with:
          path: ansible-roles
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/ansible-roles'
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Populate Vault Password File
        run: echo $PASS > ~/.vault
        shell: bash
        env:
          PASS: ${{ secrets.VAULT_PASSWORD }}
      - name: Run Playbook
        run: ansible-playbook playbooks/${{ inputs.playbook }}.yml ${{ inputs.additional_parameters }} --tags manchester --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}"
      - name: Cleanup Vault Password File
        run: rm ~/.vault
        if: always()