on:
    workflow_call:
      inputs:
        rolepath:
            required: true
            type: string
            description: non-mandatory variable used for playbooks that deploy a specific role.
        rolehosts:  
            required: true
            type: string
            description: non-mandatory variable used for playbooks that deploy to a specific inventory group.
        site:
            type: string
            description: non-mandatory variable used for playbooks that passes in site name.
            required: true
      secrets:
        sudo_password:  
        mastertoken:

jobs:
  role:
    runs-on: "{{ inputs.site }}"
    name: "{{ inputs.rolehosts}}"
    defaults:
      run:
        working-directory: infrastructure/
    steps:
      - name: Checkout Repository ("${{ github.event.repository.name }}")
        uses: actions/checkout@v4
        with:
          path: "${{ github.event.repository.name }}"
      - name: Checkout Repository (infrastructure)
        uses: actions/checkout@v4
        with:
          path: infrastructure
          token: ${{secrets.mastertoken}}
          ref: 'main'
          repository: 'epichouse/infrastructure'
      - name: Checkout Repository (bash)
        uses: actions/checkout@v4
        with:
          path: bash
          repository: 'epichouse/bash'
          ref: 'main'
          token: ${{secrets.mastertoken}}
      - name: Run Playbook
        run: ansible-playbook playbooks/deploy-role.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }} rolepath=${{ inputs.rolepath }} rolehosts=${{ inputs.rolehosts }}"
