on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        description: The mode of the workflow (deploy/destroy)
      environment:
        required: true
        type: string
        description: The environment to deploy to
    secrets:
      mastertoken:
      arm_client_id:
      arm_client_secret:
      arm_subscription_id:
      arm_tenant_id:
      azure_storage_account_name:
      azure_storage_container_name:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Azure Login
        run: az login --service-principal -u ${{secrets.ARM_CLIENT_ID}} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="key=demo.tfstate" -backend-config="use_azuread_auth=true" -backend-config="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}"
      - name: Terraform Plan (Deploy Mode)
        run: terraform plan -out=tfplan
        if: inputs.mode == 'deploy'
      - name: Terraform Plan (Destroy Mode)
        run: terraform plan -out=tfplan -destroy
        if: inputs.mode == 'destroy'
      - name: Upload Plan for Apply
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
  approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ inputs.mastertoken }}
          approvers: danshaww
          minimum-approvals: 1
          issue-title: "Terraform Approval ${{ inputs.mode }}"
          issue-body: "Please approve this Terraform ${{ inputs.mode }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: approval
    environment:
      name: ${{inputs.environment}}
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      - name: Azure Login
        run: az login --service-principal -u ${{secrets.ARM_CLIENT_ID}} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="key=demo.tfstate" -backend-config="use_azuread_auth=true" -backend-config="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}"
      - name: Terraform Apply
        run: terraform apply -auto-approve "tfplan"   
